sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
install:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer update
  - if [[ ${TRAVIS_PHP_VERSION} == "5.4" ]]; then composer require sebastian/phpcpd:dev-master#de90566 --ignore-platform-reqs php; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "5.5" ]]; then composer require sebastian/phpcpd:dev-master#de90566 --ignore-platform-reqs php; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "5.6" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "7.0" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "7.1" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "hhvm" ]]; then composer require sebastian/phpcpd:dev-master; fi
script:
  - vendor/bin/phpqa --verbose --analyzedDir ./examples/src/ --buildDir ./build/logs --report
  - vendor/bin/codecept run -v --steps  --coverage --coverage-xml --coverage-html
cache:
  directories:
    - $HOME/.composer/cache