sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
before_script:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer update
  - if [[ ${TRAVIS_PHP_VERSION} == "5.6" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "7.0" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "7.1" ]]; then composer require sebastian/phpcpd:dev-master; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "hhvm" ]]; then composer require sebastian/phpcpd:dev-master; fi
script:
  - echo ${TRAVIS_PHP_VERSION}
  - vendor/bin/phpqa --verbose --analyzedDirs ./examples/src/ --buildDir ./build/logs --report
  - if  [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ ${TRAVIS_PHP_VERSION} != "hhvm" ]]; then vendor/bin/codecept run -v --steps  --coverage --coverage-xml --coverage-html; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "hhvm" ]]; then vendor/bin/codecept run unit,acceptance -v --steps; fi
  - if [[ ${TRAVIS_PHP_VERSION} == "nightly" ]]; then vendor/bin/codecept run unit,acceptance -v --steps; fi
cache:
  directories:
    - $HOME/.composer/cache